### ISSUE TITLE
[ENHANCEMENT] Replace user-defined database queries with `$eq` operator in mongoose

### ISSUE THREAD

**Issue by sandip2224** [sandip2224/RESTful-Ecommmerce-API#9]
## Issue
This API utilizes direct database queries from users which exposes our database (MongoDB) to malicious queries. 

## Fix
Replace **direct database queries** with `$eq` operator to ensure that untrusted data is interpreted as a literal value and not as a query object. Here's a relevant screenshot on how to use $eq operator:

**Before**

![image](https://user-images.githubusercontent.com/61842142/138470448-3f3e5592-4a88-427b-aa74-b5910b139f55.png)

**After**

![image](https://user-images.githubusercontent.com/61842142/138470824-f53e669b-af23-425d-b1b1-d8fb0551f52c.png)

**Comment by ashalfarhan** [comment]
Hi @sandip2224 , can i take this up? if there's no one is working on this issue.

**Comment by sandip2224** [comment]
Sure here you go
